[package]
name = "neopoligen_parser_prototype_v36"
version = "0.0.36"
edition = "2021"

[dependencies]
html-escape = "0.2.13"
nom = "7.1.3"
nom-supreme = "0.8.0"
pretty_assertions = "1.4.0"
rstest = "0.19.0"
